version: 2

updates:
  - package-ecosystem: 'npm'
    target-branch: 'main'
    directory: '/eslint-config'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci'
    labels:
      - 'pnpm dependencies'
      - 'eslint-config'

  - package-ecosystem: 'npm'
    directory: '/prettier-config'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci'
    labels:
      - 'pnpm dependencies'
      - 'eslint-config'
