module.exports = {
  rules: {
    'brace-style': 0,
    camelcase: 0,
    'comma-spacing': 0,
    'consistent-this': 1,
    'eol-last': 1,
    'func-call-spacing': 1,
    'func-names': 0,
    'func-style': 0,
    'jsx-quotes': 0,
    'key-spacing': 0,
    'keyword-spacing': 1,
    'max-nested-callbacks': 0,
    'new-cap': 0,
    'new-parens': 1,
    'no-array-constructor': 1,
    'no-lonely-if': 0,
    'no-mixed-spaces-and-tabs': 1,
    'no-multi-spaces': 0,
    'no-nested-ternary': 0,
    'no-new-object': 1,
    'no-ternary': 0,
    'no-trailing-spaces': 0,
    'no-underscore-dangle': 0,
    'one-var': 0,
    'quote-props': 0,
    quotes: 0,
    semi: 0,
    'sort-vars': 0,
    'space-in-brackets': 0,
    'space-in-parens': 0,
    'space-infix-ops': 1,
    'space-unary-ops': [
      1,
      {
        words: true,
        nonwords: false,
      },
    ],
    'wrap-regex': 0,
  },
}
